import type { Metadata } from 'next'
import './globals.sass'
import Header from '@/components/NavBar/Header'
import Footer from '@/components/Footer/Footer'
import { ThemeProvider } from '@mui/material/styles';
import theme from '@/themes/theme';



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider theme={theme}>
          <Header />
          <main>
            {children}
          </main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
