import type { Metadata } from 'next'
import './globals.sass'
import Header from '../components/NavBar/Header'
import Footer from '../components/Footer/Footer'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(this: any, {
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header children={undefined} />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
